language: python
matrix:
  include:
  - os: osx
    language: generic
before_install:
- "./.travis/deps.sh"
script:
- "./.travis/build.sh"
after_success:
- "./.travis/deploy.sh"
deploy:
  provider: releases
  api_key:
    secure: IvGP93sWdSghUmKa7v8vdEb6FLxee7n1KWOMya5dJ+IdbCot5Lsxs6QT75HcRQ8yrG0Qu9ga/HTIk+U/SdBJX/N9tFweIouq+rqJq4q91s63oGIhhixiZJ0bA3oIJxi5cY49puLalrCXUNBhs1tCDD0CVHBxgl6V2BJ4ZOX3UBvCk90rScZWmodJWbIjL+saO/GA1ff2bXTPvZD+ddD88+a+yACmAl9j68HuuPqYY/JFvllKf0XncZuoJwKPlb48VYmXF9a1fyPiWDDSGMKZwgSuSpDnAatLm7d1zL4v9Zx2vOETKpJBI+cwvZOop5eYUIRvnyKw5uC6Bq99hERn9KgDAigdjKk5Z9FgRFJT11VQjsTkmZcsUjvIdSCguMuvQv7pYje51feG5rmJUByXh/dNskJQjY5KBYNqoivWpfsQEVmxnLhXub+KB20P1C9uAiHElTI+8/5CQbzgOI6FmmEAgBdvgU3pY7qFDJktNV28qwBhgHUrDcaFUqULr6RCoUUgl1x0FqsknKYZvNFH4ICw6Q9zymnnn9gSEI1zuPPheoUWiDQ7gqYw3v20/wYWJcEyci+uIUBBivhnznbBmwucOYacCnwm8M/Pq+VW3YSuflsB05r28fzFQ8MHuEMcX8IBbYvZgvsETiqdeFG4E7bmlc85yUmEJd2FPQGha1s=
  file: 'dist/vmo-score-$TRAVIS_TAG-OSX.zip'
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx
