"""
This is a setup.py script generated by py2applet

Usage:
    python setup_osx.py py2app
"""

from setuptools import setup

APP = ['VMO_Score/main.py']
APP_NAME = "VMO-Score"
DATA_FILES = []
OPTIONS = {'includes': ["numpy", "sklearn.neighbors.typedefs",
                        'sklearn.utils.lgamma', 'sklearn.manifold',
                        'sklearn.utils.sparsetools._graph_validation',
                        'sklearn.utils.weight_vector', 'Tkinter', 'FileDialog',
                        'tkFileDialog', 'snakes.nets', 'snakes.plugins.gv',
                        'snakes.plugins.tpn', 'snakes.plugins.pos',
                        'subprocess', 'os', 'os.path'],
           'excludes': ['PyQt4', 'PyQt5'],
           'packages': ['PIL'],
           'argv_emulation': True,
           'resources': ['./resources/dot'],
           'iconfile': './resources/icon.icns'}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
